{
 "title": "Anchor",
 "tags": [
  "signalk",
  "boat"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "signalk_navigation_position_latitude{source=\"n2k-on-ve.can-socket.43\"}",
     "legendFormat": "latitude"
    },
    {
     "expr": "signalk_navigation_position_longitude{source=\"n2k-on-ve.can-socket.43\"}",
     "legendFormat": "longitude"
    }
   ]
  },
  {
   "title": "TWS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "expr": "signalk_environment_wind_speedTrue * 1.94384",
     "legendFormat": "Mean"
    },
    {
     "expr": "max_over_time(signalk_environment_wind_speedTrue[$__interval]) * 1.94384",
     "legendFormat": "Max"
    },
    {
     "expr": "min_over_time(signalk_environment_wind_speedTrue[$__interval]) * 1.94384",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Anchor distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "signalk_navigation_anchor_currentRadius{source=\"anchoralarm\"}",
     "legendFormat": "Distance"
    }
   ]
  },
  {
   "title": "Anchor bearing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "signalk_navigation_anchor_bearingTrue{source=\"anchoralarm\"} * 57.29577951308232",
     "legendFormat": "True"
    }
   ]
  },
  {
   "title": "TWS",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "signalk_environment_wind_speedTrue * 1.94384",
     "legendFormat": "TWS"
    }
   ]
  },
  {
   "title": "TWD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "signalk_environment_wind_directionTrue * 57.29577951308232",
     "legendFormat": "True"
    }
   ]
  },
  {
   "title": "Depth below keel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "signalk_environment_depth_belowKeel",
     "legendFormat": "Mean"
    },
    {
     "expr": "max_over_time(signalk_environment_depth_belowKeel[$__interval])",
     "legendFormat": "Max"
    },
    {
     "expr": "min_over_time(signalk_environment_depth_belowKeel[$__interval])",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Water temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "signalk_environment_water_temperature - 273.15",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Depth below surface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "signalk_environment_depth_belowSurface * -1",
     "legendFormat": "Mean"
    }
   ]
  }
 ]
}