{
 "title": "Sailing",
 "tags": [
  "signalk",
  "boat"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Instantaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SOG",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signalk_navigation_speedOverGround{source=\"n2k-on-ve.can-socket.43\"} * 1.94384",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "SOG 1m",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(signalk_navigation_speedOverGround{source=\"n2k-on-ve.can-socket.43\"}[1m]) * 1.94384",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "SOG 5m",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(signalk_navigation_speedOverGround{source=\"n2k-on-ve.can-socket.43\"}[5m]) * 1.94384",
     "legendFormat": "5m"
    }
   ]
  },
  {
   "title": "PCT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signalk_performance_polarSpeedRatio * 100",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Polar",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signalk_performance_polarSpeed{source=\"signalk-polars-kraivio\"} * 1.94384",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "COG",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "signalk_navigation_courseOverGroundTrue{source=\"n2k-on-ve.can-socket.43\"} * 57.29577951308232",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Heading",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "signalk_navigation_headingTrue * 57.29577951308232",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "AWA",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "signalk_environment_wind_angleApparent * 57.29577951308232",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "AWS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(signalk_environment_wind_speedApparent[$__interval]) * 1.94384",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "TWS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(signalk_environment_wind_speedTrue[$__interval]) * 1.94384",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "TWD",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "signalk_environment_wind_directionTrue * 57.29577951308232",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "signalk_navigation_position_latitude{source=\"n2k-on-ve.can-socket.43\"}",
     "legendFormat": "latitude"
    },
    {
     "expr": "signalk_navigation_position_longitude{source=\"n2k-on-ve.can-socket.43\"}",
     "legendFormat": "longitude"
    }
   ]
  },
  { "title": "Boat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "SOG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "expr": "signalk_navigation_speedOverGround{source=\"n2k-on-ve.can-socket.43\"} * 1.94384",
     "legendFormat": "Mean"
    },
    {
     "expr": "max_over_time(signalk_navigation_speedOverGround{source=\"n2k-on-ve.can-socket.43\"}[$__interval]) * 1.94384",
     "legendFormat": "Max"
    },
    {
     "expr": "avg_over_time(signalk_navigation_speedOverGround{source=\"n2k-on-ve.can-socket.43\"}[5m]) * 1.94384",
     "legendFormat": "5m"
    },
    {
     "expr": "min_over_time(signalk_navigation_speedOverGround{source=\"n2k-on-ve.can-socket.43\"}[$__interval]) * 1.94384",
     "legendFormat": "Min"
    },
    {
     "expr": "avg_over_time(signalk_navigation_speedOverGround{source=\"n2k-on-ve.can-socket.43\"}[1m]) * 1.94384",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "STW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "expr": "signalk_navigation_speedThroughWater * 1.94384",
     "legendFormat": "Mean"
    },
    {
     "expr": "max_over_time(signalk_navigation_speedThroughWater[$__interval]) * 1.94384",
     "legendFormat": "Max"
    },
    {
     "expr": "min_over_time(signalk_navigation_speedThroughWater[$__interval]) * 1.94384",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "COG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "signalk_navigation_courseOverGroundTrue{source=\"n2k-on-ve.can-socket.43\"} * 57.29577951308232",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Heading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "signalk_navigation_headingTrue * 57.29577951308232",
     "legendFormat": "Mean"
    }
   ]
  },
  { "title": "Wind", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "TWS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "expr": "signalk_environment_wind_speedTrue * 1.94384",
     "legendFormat": "Mean"
    },
    {
     "expr": "max_over_time(signalk_environment_wind_speedTrue[$__interval]) * 1.94384",
     "legendFormat": "Max"
    },
    {
     "expr": "min_over_time(signalk_environment_wind_speedTrue[$__interval]) * 1.94384",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "AWS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "expr": "signalk_environment_wind_speedApparent * 1.94384",
     "legendFormat": "Mean"
    },
    {
     "expr": "max_over_time(signalk_environment_wind_speedApparent[$__interval]) * 1.94384",
     "legendFormat": "Max"
    },
    {
     "expr": "min_over_time(signalk_environment_wind_speedApparent[$__interval]) * 1.94384",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "TWS",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "signalk_environment_wind_speedTrue * 1.94384",
     "legendFormat": "TWS"
    }
   ]
  },
  {
   "title": "AWA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "signalk_environment_wind_angleApparent * 57.29577951308232",
     "legendFormat": "Mean"
    },
    {
     "expr": "avg_over_time(signalk_environment_wind_angleApparent[5m]) * 57.29577951308232",
     "legendFormat": "5m"
    }
   ]
  },
  {
   "title": "TWD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "signalk_environment_wind_directionTrue * 57.29577951308232",
     "legendFormat": "True"
    }
   ]
  },
  { "title": "Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Depth below keel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "signalk_environment_depth_belowKeel",
     "legendFormat": "Mean"
    },
    {
     "expr": "max_over_time(signalk_environment_depth_belowKeel[$__interval])",
     "legendFormat": "Max"
    },
    {
     "expr": "min_over_time(signalk_environment_depth_belowKeel[$__interval])",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Water temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "signalk_environment_water_temperature - 273.15",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "signalk_environment_current_setTrue * 57.29577951308232",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "expr": "signalk_environment_current_drift * 1.94384",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Spread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "(max_over_time(signalk_navigation_attitude_roll[$__interval]) - min_over_time(signalk_navigation_attitude_roll[$__interval])) * 57.29577951308232",
     "legendFormat": "Roll"
    },
    {
     "expr": "(max_over_time(signalk_navigation_attitude_pitch[$__interval]) - min_over_time(signalk_navigation_attitude_pitch[$__interval])) * 57.29577951308232",
     "legendFormat": "Pitch"
    }
   ]
  }
 ]
}