# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "uas"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Full-disk encryption (recommended on a laptop; your Ubuntu install is
  # unencrypted). Delete this block if you decide against LUKS.
  boot.initrd.luks.devices."cryptroot".device =
    "/dev/disk/by-uuid/7d26cd14-9158-420f-920b-d69fd2fbdd28";
  # Swap must be encrypted too, or hibernation writes RAM to disk in the
  # clear. The systemd initrd reuses the passphrase, so still one prompt.
  boot.initrd.luks.devices."cryptswap".device =
    "/dev/disk/by-uuid/84b6169e-d6ec-4910-9a5e-91518ceca6f6";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1bc0172e-61da-4d73-9b6a-4450736f7c3d";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd:1"
      "noatime"
      "ssd"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/1bc0172e-61da-4d73-9b6a-4450736f7c3d";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd:1"
      "noatime"
      "ssd"
      "discard=async"
      "space_cache=v2"
    ];
  };

  # /nix is where every package lives. A separate subvolume keeps it out of
  # your @ / @home snapshots (it is fully reproducible from this repo anyway).
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/1bc0172e-61da-4d73-9b6a-4450736f7c3d";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd:1"
      "noatime"
      "ssd"
      "discard=async"
      "space_cache=v2"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6FF3-CF36";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # Size >= RAM (64G) if you want hibernation; 8G otherwise.
  swapDevices = [ { device = "/dev/mapper/cryptswap"; } ];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
